# -*- coding: utf-8 -*-
"""Python Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YNJx2CMObRQqQvkDDMxIEISZfGs7npwU
"""

print('Hello World 7')

'Hello World 8'

'Hello World 7'

type('Hello World 7')

"My name is Greg and I am 23 years old"

"23" + "4"

23 + 4

"hello" + " world"

"hello" + "hi"
print('hi')

3 - 2

type(3)

type(3.2)

type(3 + 2)

type(3.2 + 4.7)

4 - 3

3.2 - 1.0

4 * 3

2.1 * 3.2

4 / 3

1 / 1

3.2 / 1.6

3 // 2

5 // 2

5 % 2

7 % 3

5*5*5

5 ** 3

print(5 ** 3)

y = 5

y

y = 4

y

y = "tree"

y

"tree"

True

False

"True"

type(True)

4 > 3

not True

not False

2 >= 2

2 != 3

3 != 2

3 == 2

"hi" == "hi"

3.2 > 5

True

x = 9

if x > 7:
  print(1)
  print(2)

print(3)

grocery_list = ["banana", "orange", "blueberries"]

grocery_list

grocery_list.append("fruit")

grocery_list

type(grocery_list)

for item in grocery_list:
  print(item)

grocery_list[4]

for i in range(len(grocery_list)):
  print(grocery_list[i])

list(range(len(grocery_list)))

len(grocery_list)

for i, item in enumerate(grocery_list):
  print(i, item)

i = 0
i += 1

i

i -= 1

i

grocery_list

j = len(grocery_list) - 1

while j >= 0:
  print(grocery_list[j])
  j -= 1

print('end')

i = 0

while i < len(grocery_list):
  print(grocery_list[i])
  i += 1

age = 20

if age <= 1:
  print("Newborn")
elif (age >= 13) and (age <= 19):
  print("Teen")
else:
  print("Not newborn and not teen")

print('end')

True or True

False and False

(3 > 4) and (4 < 5)

(3 > 4) or (4 < 5)

print("Hi 2")

def our_print(s):
  print(z)
  print(s + " hello")

r = "Hello"
our_print(r)

r

s = 87

s

z = 42

def times_2(x):
  return x*2

b = 4
times_2(b)

b

10

print(None)

def append_4_to_list(lst):
  lst.append(4)

a = [1, 2, 3]

append_4_to_list(a)

a

b = a

b

a is b

a is [1, 2, 3, 4]

a[0] = 7

a

b[2] = 12

b

a

from copy import deepcopy

b = deepcopy(a)

a

b

a[0] = 14

a

b

q = 5
q

w = q
w

q = 7
q

w

def add_1(x):
  x = [1, 2]
  print(x is a)
  x.append(4)
  return x

a = [1, 2, 3]
add_1(a)

a

def add(a, b=4, c=5):
  return (a * b) + c


add(a=5, c=2)

# !ls

p = 'a_test.txt'

with open(p, 'r') as f:
  for line in f:
    print(line.rstrip())

with open('new_file.txt', 'a') as f:
  f.write("\nHello")

class Human:
  '''
  This is a class that represents a simplified Human.

  It takes their age as an int, and their name as a str.
  '''
  def __init__(self, age, name):
    self._age = age
    self._name = name

  def __str__(self):
    return "A human with name " + self._name + "." + " Their age is " + str(self._age) + "."

  def __repr__(self):
    return "A human with name " + self._name + "." + " Their age is " + str(self._age) + "."

  def older_younger_than(self, age):
    if self._age > age:
      print("Our age is bigger than their age.")
    elif self._age == age:
      print("Our age is equal to their age.")
    else:
      print("Our age is less than their age.")

h = Human(age=4, name="Greg")

h

help(Human)

h._age

help(h)

a = 4
help(6)

h._name

h.__str__()

h.older_younger_than(5)

# The following is a function that multiplies two numbers

def mult(a, b):
  '''
  mult(a, b) is a function which returns the multiplication
  of a and b.

  a: Number
  b: Number
  '''
  return a*b

mult(4, -3.2)

help(mult)

help(print)

l = [1, 2, 3]

l.append(4)

l

l.insert(0, "Hi")

l

l.append(4)

l

l.count(7)

l.reverse()

l

l.remove(3)

l

l = []

for i in range(5):
  for j in range(3):
    if (i + j) % 2 == 0:
      l.append(i + j)

l

d = {'Apple': "It's a fruit that is high in Vitamin C",
     'Banana': "It's a fruit that is high in potassium"}

d

d['Apple']

d['Banana']

d['Banana'] = "It's a vegetable that is high in potassium"

d

del d['Banana']

d

d['Cucumber'] = "This is a long cylindrical fruit with a boring taste"

d

for k in d.keys():
  v = d[k]
  print(k, v)

d2 = {0: 'Greg', 1: 'Sarah', 2: 'Tom'}

d2

d2[1]

name = "Greg"
fav_num = 23

f"Hey {name} how is it going? My favorite person is {h}"

"Hey {0} how is it going {0}? My favorite person is {1}".format(name, h)

for c in "Greg":
  print(type(c))

"My name is Greg".split(" ")

"Greg".isnumeric()

"452".isnumeric()

"4G6".isnumeric()

"HELLO THERE".lower()

"HEllO THeRE".upper()

s = "Hello"

s[4]

len(s)

l = [1, 2]

l[0] = 5

l

s[0] = "t"

s

t = (0, 1)

t

t[1]

for item in t:
  print(item)

t[0] = 5

{1, 1, 2, -4}

set('Greg is a great guy')

set([1, 1, 2, 2, 3, -5, 6, 4])

set()

sorted([2, 1, 4])

t = (1, 2, 3)

try:
  print("Hi")
  t[0] = 1
  print("Hello")
except:
  print("Caught it")

result = input("Hey, please give us a number")

print(f"The result is {result}.")

type(result)

result.isnumeric()

l = [x for x in range(5)]

l

l = [x**2 for x in range(5)]

l

l = [x if (x%2) == 0 else 5 for x in [4, 1, 6, 12]]

l

[0] * 5

[1, 2] + [5, 4, 7]

for a, b in zip(range(3), range(4, 7)):
  print(a, b)

[(a, b) for a, b in zip(range(3), range(4, 7))]

{a:b for a, b in zip(range(3), range(4, 7))}

chr(65)

chr(97)

ord('A')

ord('a')

chr(99)

{k:chr(k+64) for k in range(1, 27)}

import copy as cp

a = [1, 2, 3]

b = cp.deepcopy(a)

b

a is b

# import numpy as np

# np

# !pip list

# num

# !ls

# !python test.py

